### ISSUE TITLE
org.apache.lucene.index.CorruptIndexException: codec mismatch

### ISSUE THREAD

**Issue by shijiebei2009** [DDTH/redir#1]
When I using this project , when I searching after index , I got this message:

"C:\Program Files\Java\jdk1.8.0_45\bin\java" -Didea.launcher.port=7535 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_45\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\zipfs.jar;D:\TestRedis\target\classes;D:\apache-maven-3.3.3\repo\junit\junit\4.12\junit-4.12.jar;D:\apache-maven-3.3.3\repo\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\apache-maven-3.3.3\repo\ch\qos\logback\logback-classic\1.1.3\logback-classic-1.1.3.jar;D:\apache-maven-3.3.3\repo\ch\qos\logback\logback-core\1.1.3\logback-core-1.1.3.jar;D:\apache-maven-3.3.3\repo\org\slf4j\slf4j-api\1.7.12\slf4j-api-1.7.12.jar;D:\apache-maven-3.3.3\repo\org\slf4j\log4j-over-slf4j\1.7.12\log4j-over-slf4j-1.7.12.jar;D:\apache-maven-3.3.3\repo\org\apache\lucene\lucene-analyzers-common\5.2.1\lucene-analyzers-common-5.2.1.jar;D:\apache-maven-3.3.3\repo\org\apache\lucene\lucene-core\5.2.1\lucene-core-5.2.1.jar;D:\apache-maven-3.3.3\repo\org\apache\lucene\lucene-queryparser\5.2.1\lucene-queryparser-5.2.1.jar;D:\apache-maven-3.3.3\repo\org\apache\lucene\lucene-sandbox\5.2.1\lucene-sandbox-5.2.1.jar;D:\apache-maven-3.3.3\repo\com\github\ddth\ddth-commons\0.3.2.1\ddth-commons-0.3.2.1.jar;D:\apache-maven-3.3.3\repo\com\google\guava\guava\14.0\guava-14.0.jar;D:\apache-maven-3.3.3\repo\jboss\jboss-serialization\4.2.2.GA\jboss-serialization-4.2.2.GA.jar;D:\apache-maven-3.3.3\repo\trove\trove\1.0.2\trove-1.0.2.jar;D:\apache-maven-3.3.3\repo\com\github\ddth\ddth-dao\0.4.0.2\ddth-dao-0.4.0.2.jar;D:\apache-maven-3.3.3\repo\com\github\ddth\ddth-cache-adapter\0.2.0.2\ddth-cache-adapter-0.2.0.2.jar;D:\apache-maven-3.3.3\repo\com\github\ddth\ddth-cql-utils\0.2.0.1\ddth-cql-utils-0.2.0.1.jar;D:\apache-maven-3.3.3\repo\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;D:\apache-maven-3.3.3\repo\org\apache\commons\commons-pool2\2.3\commons-pool2-2.3.jar;D:\apache-maven-3.3.3\repo\com\datastax\cassandra\cassandra-driver-core\2.1.1\cassandra-driver-core-2.1.1.jar;D:\apache-maven-3.3.3\repo\io\netty\netty\3.9.0.Final\netty-3.9.0.Final.jar;D:\apache-maven-3.3.3\repo\com\codahale\metrics\metrics-core\3.0.2\metrics-core-3.0.2.jar;D:\apache-maven-3.3.3\repo\org\xerial\snappy\snappy-java\1.0.5\snappy-java-1.0.5.jar;D:\apache-maven-3.3.3\repo\net\jpountz\lz4\lz4\1.2.0\lz4-1.2.0.jar;D:\apache-maven-3.3.3\repo\org\springframework\spring-jdbc\3.2.4.RELEASE\spring-jdbc-3.2.4.RELEASE.jar;D:\apache-maven-3.3.3\repo\org\springframework\spring-beans\3.2.4.RELEASE\spring-beans-3.2.4.RELEASE.jar;D:\apache-maven-3.3.3\repo\org\springframework\spring-core\3.2.4.RELEASE\spring-core-3.2.4.RELEASE.jar;D:\apache-maven-3.3.3\repo\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;D:\apache-maven-3.3.3\repo\org\springframework\spring-tx\3.2.4.RELEASE\spring-tx-3.2.4.RELEASE.jar;D:\apache-maven-3.3.3\repo\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;D:\apache-maven-3.3.3\repo\redis\clients\jedis\2.7.2\jedis-2.7.2.jar;D:\apache-maven-3.3.3\repo\com\fasterxml\jackson\core\jackson-annotations\2.6.0\jackson-annotations-2.6.0.jar;D:\apache-maven-3.3.3\repo\com\fasterxml\jackson\core\jackson-databind\2.6.0\jackson-databind-2.6.0.jar;D:\apache-maven-3.3.3\repo\com\fasterxml\jackson\core\jackson-core\2.6.0\jackson-core-2.6.0.jar;D:\apache-maven-3.3.3\repo\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\apache-maven-3.3.3\repo\com\alibaba\fastjson\1.2.16\fastjson-1.2.16.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.2\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain Demo
org.apache.lucene.index.CorruptIndexException: codec mismatch: actual codec=segments vs expected codec=Lucene50SegmentInfo (resource=BufferedChecksumIndexInput(_0.si))
    at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:209)
    at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:199)
    at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:256)
    at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.read(Lucene50SegmentInfoFormat.java:86)
    at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:326)
    at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:830)
    at Demo.main(Demo.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
    Suppressed: org.apache.lucene.index.CorruptIndexException: codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(_0.si))
        at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:416)
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:331)
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:379)
        at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.read(Lucene50SegmentInfoFormat.java:117)
        ... 8 more

Process finished with exit code 0

I don't know why?

**Comment by btnguyen2k** [comment]
This error means your index is corrupted. Mostly because of different versions of Lucene?
Which Lucene version are you using and can you post your code if you don't mind?

Regards,
Thanh Nguyen

**Comment by shijiebei2009** [comment]
first step, run QndRedisDirIndex, it prints Finished in 0.31 sec
second step, run QndRedisDirIndex again, it prints 
[segments_1, _0.cfs, _0.cfe, _0.si]before index
[_0.cfe, segments_1, _0.cfs, _0.si]after index
Exception in thread "main" java.lang.NullPointerException
    at com.github.ddth.com.redir.RedisDirectory$RedisIndexInput.readByte(RedisDirectory.java:660)
    at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41)
    at org.apache.lucene.store.DataInput.readInt(DataInput.java:101)
    at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:195)
    at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:256)
    at org.apache.lucene.codecs.lucene50.Lucene50CompoundReader.readEntries(Lucene50CompoundReader.java:94)
    at org.apache.lucene.codecs.lucene50.Lucene50CompoundReader.<init>(Lucene50CompoundReader.java:69)
    at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.getCompoundReader(Lucene50CompoundFormat.java:71)
    at org.apache.lucene.index.IndexWriter.readFieldInfos(IndexWriter.java:907)
    at org.apache.lucene.index.IndexWriter.getFieldNumberMap(IndexWriter.java:924)
    at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:854)
    at com.github.ddth.com.redir.qnd.QndRedisDirIndex.main(QndRedisDirIndex.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
    Suppressed: org.apache.lucene.index.CorruptIndexException: checksum status indeterminate: unexpected exception (resource=BufferedChecksumIndexInput(_0.cfe))
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:388)
        at org.apache.lucene.codecs.lucene50.Lucene50CompoundReader.readEntries(Lucene50CompoundReader.java:112)
        ... 11 more
    Caused by: java.lang.NullPointerException
        at com.github.ddth.com.redir.RedisDirectory$RedisIndexInput.readByte(RedisDirectory.java:660)
        at com.github.ddth.com.redir.RedisDirectory$RedisIndexInput.readBytes(RedisDirectory.java:673)
        at org.apache.lucene.store.BufferedChecksumIndexInput.readBytes(BufferedChecksumIndexInput.java:49)
        at org.apache.lucene.store.DataInput.readBytes(DataInput.java:87)
        at org.apache.lucene.store.DataInput.skipBytes(DataInput.java:350)
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:375)
        ... 12 more

**Comment by shijiebei2009** [comment]
`<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.java>1.7</version.java>
        <version.lucene>5.2.1</version.lucene>
        <version.slf4j>1.7.12</version.slf4j>
        <version.jackson>2.6.0</version.jackson>
</properties>`

**Comment by shijiebei2009** [comment]
another experiment
first step, run QndRedisDirIndex, it prints 
[]before index
[segments_1, _0.cfe, _0.cfs, _0.si]after index
Finished in 0.36 sec
second step, run QndRedisDirSearch, it prints 
Exception in thread "main" java.lang.NullPointerException
    at com.github.ddth.com.redir.RedisDirectory$RedisIndexInput.readByte(RedisDirectory.java:660)
    at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41)
    at org.apache.lucene.store.DataInput.readInt(DataInput.java:101)
    at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:195)
    at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:256)
    at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.read(Lucene50SegmentInfoFormat.java:86)
    at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:326)
    at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:53)
    at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:50)
    at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:660)
    at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:50)
    at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
    at com.github.ddth.com.redir.qnd.QndRedisDirSearch.main(QndRedisDirSearch.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
    Suppressed: org.apache.lucene.index.CorruptIndexException: checksum status indeterminate: unexpected exception (resource=BufferedChecksumIndexInput(_0.si))
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:388)
        at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.read(Lucene50SegmentInfoFormat.java:117)
        ... 12 more
    Caused by: java.lang.NullPointerException
        at com.github.ddth.com.redir.RedisDirectory$RedisIndexInput.readByte(RedisDirectory.java:660)
        at com.github.ddth.com.redir.RedisDirectory$RedisIndexInput.readBytes(RedisDirectory.java:673)
        at org.apache.lucene.store.BufferedChecksumIndexInput.readBytes(BufferedChecksumIndexInput.java:49)
        at org.apache.lucene.store.DataInput.readBytes(DataInput.java:87)
        at org.apache.lucene.store.DataInput.skipBytes(DataInput.java:350)
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:375)
        ... 13 more
all the classes are your test directory classes.

**Comment by btnguyen2k** [comment]
Hi @shijiebei2009 

I cant reproduce your error. Also I dont seem to find where in the code that prints "before index" and "after index".

I ran the same test using command line:

`mvn clean package exec:java -Dexec.mainClass="com.github.ddth.com.redir.qnd.QndRedisDirIndex" -Dexec.classpathScope=test`
Finished in 1.495 sec

and `mvn clean package exec:java -Dexec.mainClass="com.github.ddth.com.redir.qnd.QndRedisDirSearch" -Dexec.classpathScope=test`
Hits:1
Document<stored,indexed,tokenized,omitNorms,indexOptions=DOCS<id:thanhnb>>

The result seems normal to me.

**Comment by shijiebei2009** [comment]
I wonder to know, is there something wrong if you run QndRedisDirIndex twice continuously

**Comment by btnguyen2k** [comment]
I ran QndRedisDirIndex several times using command:
`mvn exec:java -Dexec.mainClass="com.github.ddth.com.redir.qnd.QndRedisDirIndex" -Dexec.classpathScope=test`
All runs were successful on my laptop.

Cheers,
